### ISSUE TITLE
crash when I want to open the skin settings in minecraft version 1.19.3 with fabric and quilt

### ISSUE THREAD

**Issue by bohanubis** [zatrit/openmcskins#11]
so when I enter into the mod configuration it works
but If I enter from the skin button minecraft crashes

this is the log:
```
[12:17:15] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:497) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1222) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4185$class_5316
	at r.a(Unknown Source) ~[openmcskins-1.3.8-optimized.jar:?]
	at net.minecraft.class_440.handler$zjn004$init(class_440.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_440.method_25426(class_440.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1049) ~[client-intermediary.jar:?]
	at net.minecraft.class_429.method_47624(class_429.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_7838.method_25402(class_7838.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	... 22 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4185$class_5316
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at r.a(Unknown Source) ~[openmcskins-1.3.8-optimized.jar:?]
	at net.minecraft.class_440.handler$zjn004$init(class_440.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_440.method_25426(class_440.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1049) ~[client-intermediary.jar:?]
	at net.minecraft.class_429.method_47624(class_429.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_7838.method_25402(class_7838.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	... 22 more
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2022-12-30 12:17:15
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: net/minecraft/class_4185$class_5316
	at r.a(Unknown Source)
	at net.minecraft.class_440.handler$zjn004$init(class_440.java)
	at net.minecraft.class_440.method_25426(class_440.java:35)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_429.method_47624(class_429.java:172)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_7838.method_25402(class_7838.java:155)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4185$class_5316
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at r.a(Unknown Source)
	at net.minecraft.class_440.handler$zjn004$init(class_440.java)
	at net.minecraft.class_440.method_25426(class_440.java:35)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_429.method_47624(class_429.java:172)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_7838.method_25402(class_7838.java:155)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Java Version: 18.0.2.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8000m
	Fabric Mods: 
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.2.0
			coat: Coat 1.0.0-beta.19+mc22w44a
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.0
		fabric-api: Fabric API 0.70.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.1+f1e4495b85
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.10+99f9db8085
			fabric-command-api-v1: Fabric Command API (v1) 1.2.20+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.16+99f9db8085
			fabric-commands-v0: Fabric Commands (v0) 0.2.37+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.45+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.2+33a4e2d785
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.38+f1e4495b85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.40+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.6+99f9db8085
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.9+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.29+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.27+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.15+99f9db8085
			fabric-networking-v0: Fabric Networking (v0) 0.3.32+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.1+f1e4495b85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.2+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.1+afca2f3e85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.24+99f9db8085
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.1+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.11+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.13+f1e4495b85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.2.0+1d37d50285
		fabricloader: Fabric Loader 0.14.12
		java: OpenJDK 64-Bit Server VM 18
		minecraft: Minecraft 1.19.3
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 5.0.2
		openmcskins: OpenMCSkins 1.3.7
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

**Comment by zatrit** [comment]
I wrote this mod when I was not particularly good at programming, so it has a lot of bugs that I can not fix. Recently I started to actively rewrite this mod from scratch, and if I succeed, I will publish it and it will be better and with fewer bugs. I apologize for the bugs in the current version of the mod.
